namespace LanguageMasteryChallenges.Problems
{
    /*
     * The sequence of triangle numbers is generated by adding the natural numbers. 
     * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
     * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
     * Let us list the factors of the first seven triangle numbers:
     * 1: 1
     * 3: 1,3
     * 6: 1,2,3,6
     * 10: 1,2,5,10
     * 15: 1,3,5,15
     * 21: 1,3,7,21
     * 28: 1,2,4,7,14,28
     * We can see that 28 is the first triangle number to have over five divisors.
     * What is the value of the first triangle number to have over five hundred divisors?
    */

    public class Problem12
    {
        private static bool IsTriangleNumber(int num)
        {
            double x = Math.Sqrt(8 * num + 1);
            return x == (int)x;
        }

        private static int GetNumberOfDivisors(int num)
        {
            if (!IsTriangleNumber(num)) { return 0; }

            List<int> result = new List<int>();
            
            for (int i = 1; i <= Math.Sqrt(num); i++)
            {
                if (num % i == 0)
                {
                    result.Add(i);
                    result.Add(num / i);
                }
            }

            return result.Count;
        }

        private static int FirstTriangleNumberWithOver500Divisors()
        {
            int triangleNumber = 1;
            int count = 1;

            while (GetNumberOfDivisors(triangleNumber) <= 500)
            {
                count++;
                triangleNumber += count;
            }

            return triangleNumber;
        }

        public static long Solution() => FirstTriangleNumberWithOver500Divisors();
    }
}