namespace LanguageMasteryChallenges.Problems
{
    /*
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
     * By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
     * find the sum of the even-valued terms.
    */

    public class Problem2
    {
        private static int Fibonacci()
        {
            int previous = 0;
            int curr = 1;
            int fibonacciNumber = 0;
            int retVal = 0;

            while(fibonacciNumber <= 4_000_000)
            {
                if(fibonacciNumber % 2 == 0) { retVal += fibonacciNumber; }

                fibonacciNumber = curr + previous;

                previous = curr;
                curr = fibonacciNumber;
            }

            return retVal;
        }

        public static int Solution()
        {
            return Fibonacci();
        }
    }
}